// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package github is a generated GoMock package.
package github

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	github0 "github.com/google/go-github/github"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetPullRequest mocks base method
func (m *MockClient) GetPullRequest(ctx context.Context, c *Context) (*github0.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequest", ctx, c)
	ret0, _ := ret[0].(*github0.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequest indicates an expected call of GetPullRequest
func (mr *MockClientMockRecorder) GetPullRequest(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequest", reflect.TypeOf((*MockClient)(nil).GetPullRequest), ctx, c)
}

// GetPullRequestComments mocks base method
func (m *MockClient) GetPullRequestComments(ctx context.Context, c *Context) ([]*github0.PullRequestComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestComments", ctx, c)
	ret0, _ := ret[0].([]*github0.PullRequestComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestComments indicates an expected call of GetPullRequestComments
func (mr *MockClientMockRecorder) GetPullRequestComments(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestComments", reflect.TypeOf((*MockClient)(nil).GetPullRequestComments), ctx, c)
}

// GetPullRequestPatch mocks base method
func (m *MockClient) GetPullRequestPatch(ctx context.Context, c *Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestPatch", ctx, c)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestPatch indicates an expected call of GetPullRequestPatch
func (mr *MockClientMockRecorder) GetPullRequestPatch(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestPatch", reflect.TypeOf((*MockClient)(nil).GetPullRequestPatch), ctx, c)
}

// CreateReview mocks base method
func (m *MockClient) CreateReview(ctx context.Context, c *Context, review *github0.PullRequestReviewRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReview", ctx, c, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReview indicates an expected call of CreateReview
func (mr *MockClientMockRecorder) CreateReview(ctx, c, review interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReview", reflect.TypeOf((*MockClient)(nil).CreateReview), ctx, c, review)
}

// SetCommitStatus mocks base method
func (m *MockClient) SetCommitStatus(ctx context.Context, c *Context, ref string, status Status, desc, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCommitStatus", ctx, c, ref, status, desc, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCommitStatus indicates an expected call of SetCommitStatus
func (mr *MockClientMockRecorder) SetCommitStatus(ctx, c, ref, status, desc, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCommitStatus", reflect.TypeOf((*MockClient)(nil).SetCommitStatus), ctx, c, ref, status, desc, url)
}
