run:
  timeout: 2m

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 140
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch

linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - prealloc
    - gosec
    - gochecknoglobals
    - gochecknoinits
    - scopelint
    - dupl
    - interfacer
    - gosimple

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.21.x # use fixed version to not introduce new linters unexpectedly
