// Code generated by go-queryset. DO NOT EDIT.
package models

import (
	"errors"
	"fmt"
	"time"

	"github.com/jinzhu/gorm"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set PullRequestAnalysisQuerySet

// PullRequestAnalysisQuerySet is an queryset type for PullRequestAnalysis
type PullRequestAnalysisQuerySet struct {
	db *gorm.DB
}

// NewPullRequestAnalysisQuerySet constructs new PullRequestAnalysisQuerySet
func NewPullRequestAnalysisQuerySet(db *gorm.DB) PullRequestAnalysisQuerySet {
	return PullRequestAnalysisQuerySet{
		db: db.Model(&PullRequestAnalysis{}),
	}
}

func (qs PullRequestAnalysisQuerySet) w(db *gorm.DB) PullRequestAnalysisQuerySet {
	return NewPullRequestAnalysisQuerySet(db)
}

// All is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) All(ret *[]PullRequestAnalysis) error {
	return qs.db.Find(ret).Error
}

// CommitSHAEq is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) CommitSHAEq(commitSHA string) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("commit_sha = ?", commitSHA))
}

// CommitSHAIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) CommitSHAIn(commitSHA ...string) PullRequestAnalysisQuerySet {
	if len(commitSHA) == 0 {
		qs.db.AddError(errors.New("must at least pass one commitSHA in CommitSHAIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("commit_sha IN (?)", commitSHA))
}

// CommitSHANe is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) CommitSHANe(commitSHA string) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("commit_sha != ?", commitSHA))
}

// CommitSHANotIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) CommitSHANotIn(commitSHA ...string) PullRequestAnalysisQuerySet {
	if len(commitSHA) == 0 {
		qs.db.AddError(errors.New("must at least pass one commitSHA in CommitSHANotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("commit_sha NOT IN (?)", commitSHA))
}

// Count is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// Create is an autogenerated method
// nolint: dupl
func (o *PullRequestAnalysis) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) CreatedAtEq(createdAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at = ?", createdAt))
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) CreatedAtGt(createdAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at > ?", createdAt))
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) CreatedAtGte(createdAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at >= ?", createdAt))
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) CreatedAtLt(createdAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at < ?", createdAt))
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) CreatedAtLte(createdAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at <= ?", createdAt))
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) CreatedAtNe(createdAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at != ?", createdAt))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) Delete() error {
	return qs.db.Delete(PullRequestAnalysis{}).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *PullRequestAnalysis) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// DeletedAtEq is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) DeletedAtEq(deletedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at = ?", deletedAt))
}

// DeletedAtGt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) DeletedAtGt(deletedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at > ?", deletedAt))
}

// DeletedAtGte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) DeletedAtGte(deletedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at >= ?", deletedAt))
}

// DeletedAtIsNotNull is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) DeletedAtIsNotNull() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NOT NULL"))
}

// DeletedAtIsNull is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) DeletedAtIsNull() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NULL"))
}

// DeletedAtLt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) DeletedAtLt(deletedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at < ?", deletedAt))
}

// DeletedAtLte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) DeletedAtLte(deletedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at <= ?", deletedAt))
}

// DeletedAtNe is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) DeletedAtNe(deletedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at != ?", deletedAt))
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GetUpdater() PullRequestAnalysisUpdater {
	return NewPullRequestAnalysisUpdater(qs.db)
}

// GithubDeliveryGUIDEq is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubDeliveryGUIDEq(githubDeliveryGUID string) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_delivery_guid = ?", githubDeliveryGUID))
}

// GithubDeliveryGUIDIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubDeliveryGUIDIn(githubDeliveryGUID ...string) PullRequestAnalysisQuerySet {
	if len(githubDeliveryGUID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubDeliveryGUID in GithubDeliveryGUIDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_delivery_guid IN (?)", githubDeliveryGUID))
}

// GithubDeliveryGUIDNe is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubDeliveryGUIDNe(githubDeliveryGUID string) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_delivery_guid != ?", githubDeliveryGUID))
}

// GithubDeliveryGUIDNotIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubDeliveryGUIDNotIn(githubDeliveryGUID ...string) PullRequestAnalysisQuerySet {
	if len(githubDeliveryGUID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubDeliveryGUID in GithubDeliveryGUIDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_delivery_guid NOT IN (?)", githubDeliveryGUID))
}

// GithubPullRequestNumberEq is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubPullRequestNumberEq(githubPullRequestNumber int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number = ?", githubPullRequestNumber))
}

// GithubPullRequestNumberGt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubPullRequestNumberGt(githubPullRequestNumber int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number > ?", githubPullRequestNumber))
}

// GithubPullRequestNumberGte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubPullRequestNumberGte(githubPullRequestNumber int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number >= ?", githubPullRequestNumber))
}

// GithubPullRequestNumberIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubPullRequestNumberIn(githubPullRequestNumber ...int) PullRequestAnalysisQuerySet {
	if len(githubPullRequestNumber) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubPullRequestNumber in GithubPullRequestNumberIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_pull_request_number IN (?)", githubPullRequestNumber))
}

// GithubPullRequestNumberLt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubPullRequestNumberLt(githubPullRequestNumber int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number < ?", githubPullRequestNumber))
}

// GithubPullRequestNumberLte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubPullRequestNumberLte(githubPullRequestNumber int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number <= ?", githubPullRequestNumber))
}

// GithubPullRequestNumberNe is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubPullRequestNumberNe(githubPullRequestNumber int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number != ?", githubPullRequestNumber))
}

// GithubPullRequestNumberNotIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubPullRequestNumberNotIn(githubPullRequestNumber ...int) PullRequestAnalysisQuerySet {
	if len(githubPullRequestNumber) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubPullRequestNumber in GithubPullRequestNumberNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_pull_request_number NOT IN (?)", githubPullRequestNumber))
}

// GithubRepoIDEq is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubRepoIDEq(githubRepoID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id = ?", githubRepoID))
}

// GithubRepoIDGt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubRepoIDGt(githubRepoID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id > ?", githubRepoID))
}

// GithubRepoIDGte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubRepoIDGte(githubRepoID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id >= ?", githubRepoID))
}

// GithubRepoIDIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubRepoIDIn(githubRepoID ...uint) PullRequestAnalysisQuerySet {
	if len(githubRepoID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubRepoID in GithubRepoIDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_repo_id IN (?)", githubRepoID))
}

// GithubRepoIDLt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubRepoIDLt(githubRepoID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id < ?", githubRepoID))
}

// GithubRepoIDLte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubRepoIDLte(githubRepoID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id <= ?", githubRepoID))
}

// GithubRepoIDNe is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubRepoIDNe(githubRepoID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id != ?", githubRepoID))
}

// GithubRepoIDNotIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) GithubRepoIDNotIn(githubRepoID ...uint) PullRequestAnalysisQuerySet {
	if len(githubRepoID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubRepoID in GithubRepoIDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_repo_id NOT IN (?)", githubRepoID))
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) IDEq(ID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("id = ?", ID))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) IDGt(ID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("id > ?", ID))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) IDGte(ID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("id >= ?", ID))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) IDIn(ID ...uint) PullRequestAnalysisQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id IN (?)", ID))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) IDLt(ID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("id < ?", ID))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) IDLte(ID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("id <= ?", ID))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) IDNe(ID uint) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("id != ?", ID))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) IDNotIn(ID ...uint) PullRequestAnalysisQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id NOT IN (?)", ID))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) Limit(limit int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) Offset(offset int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs PullRequestAnalysisQuerySet) One(ret *PullRequestAnalysis) error {
	return qs.db.First(ret).Error
}

// OrderAscByCreatedAt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderAscByCreatedAt() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("created_at ASC"))
}

// OrderAscByDeletedAt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderAscByDeletedAt() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("deleted_at ASC"))
}

// OrderAscByGithubPullRequestNumber is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderAscByGithubPullRequestNumber() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("github_pull_request_number ASC"))
}

// OrderAscByGithubRepoID is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderAscByGithubRepoID() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("github_repo_id ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderAscByID() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByReportedIssuesCount is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderAscByReportedIssuesCount() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("reported_issues_count ASC"))
}

// OrderAscByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderAscByUpdatedAt() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("updated_at ASC"))
}

// OrderDescByCreatedAt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderDescByCreatedAt() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("created_at DESC"))
}

// OrderDescByDeletedAt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderDescByDeletedAt() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("deleted_at DESC"))
}

// OrderDescByGithubPullRequestNumber is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderDescByGithubPullRequestNumber() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("github_pull_request_number DESC"))
}

// OrderDescByGithubRepoID is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderDescByGithubRepoID() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("github_repo_id DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderDescByID() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByReportedIssuesCount is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderDescByReportedIssuesCount() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("reported_issues_count DESC"))
}

// OrderDescByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) OrderDescByUpdatedAt() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Order("updated_at DESC"))
}

// PreloadGithubRepo is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) PreloadGithubRepo() PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Preload("GithubRepo"))
}

// ReportedIssuesCountEq is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ReportedIssuesCountEq(reportedIssuesCount int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count = ?", reportedIssuesCount))
}

// ReportedIssuesCountGt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ReportedIssuesCountGt(reportedIssuesCount int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count > ?", reportedIssuesCount))
}

// ReportedIssuesCountGte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ReportedIssuesCountGte(reportedIssuesCount int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count >= ?", reportedIssuesCount))
}

// ReportedIssuesCountIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ReportedIssuesCountIn(reportedIssuesCount ...int) PullRequestAnalysisQuerySet {
	if len(reportedIssuesCount) == 0 {
		qs.db.AddError(errors.New("must at least pass one reportedIssuesCount in ReportedIssuesCountIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("reported_issues_count IN (?)", reportedIssuesCount))
}

// ReportedIssuesCountLt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ReportedIssuesCountLt(reportedIssuesCount int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count < ?", reportedIssuesCount))
}

// ReportedIssuesCountLte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ReportedIssuesCountLte(reportedIssuesCount int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count <= ?", reportedIssuesCount))
}

// ReportedIssuesCountNe is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ReportedIssuesCountNe(reportedIssuesCount int) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count != ?", reportedIssuesCount))
}

// ReportedIssuesCountNotIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ReportedIssuesCountNotIn(reportedIssuesCount ...int) PullRequestAnalysisQuerySet {
	if len(reportedIssuesCount) == 0 {
		qs.db.AddError(errors.New("must at least pass one reportedIssuesCount in ReportedIssuesCountNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("reported_issues_count NOT IN (?)", reportedIssuesCount))
}

// ResultJSONEq is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ResultJSONEq(resultJSON []byte) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("result_json = ?", resultJSON))
}

// ResultJSONIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ResultJSONIn(resultJSON ...[]byte) PullRequestAnalysisQuerySet {
	if len(resultJSON) == 0 {
		qs.db.AddError(errors.New("must at least pass one resultJSON in ResultJSONIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("result_json IN (?)", resultJSON))
}

// ResultJSONNe is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ResultJSONNe(resultJSON []byte) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("result_json != ?", resultJSON))
}

// ResultJSONNotIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) ResultJSONNotIn(resultJSON ...[]byte) PullRequestAnalysisQuerySet {
	if len(resultJSON) == 0 {
		qs.db.AddError(errors.New("must at least pass one resultJSON in ResultJSONNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("result_json NOT IN (?)", resultJSON))
}

// SetCommitSHA is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetCommitSHA(commitSHA string) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.CommitSHA)] = commitSHA
	return u
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetCreatedAt(createdAt time.Time) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.CreatedAt)] = createdAt
	return u
}

// SetDeletedAt is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetDeletedAt(deletedAt *time.Time) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.DeletedAt)] = deletedAt
	return u
}

// SetGithubDeliveryGUID is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetGithubDeliveryGUID(githubDeliveryGUID string) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.GithubDeliveryGUID)] = githubDeliveryGUID
	return u
}

// SetGithubPullRequestNumber is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetGithubPullRequestNumber(githubPullRequestNumber int) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.GithubPullRequestNumber)] = githubPullRequestNumber
	return u
}

// SetGithubRepo is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetGithubRepo(githubRepo Repo) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.GithubRepo)] = githubRepo
	return u
}

// SetGithubRepoID is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetGithubRepoID(githubRepoID uint) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.GithubRepoID)] = githubRepoID
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetID(ID uint) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.ID)] = ID
	return u
}

// SetReportedIssuesCount is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetReportedIssuesCount(reportedIssuesCount int) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.ReportedIssuesCount)] = reportedIssuesCount
	return u
}

// SetResultJSON is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetResultJSON(resultJSON []byte) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.ResultJSON)] = resultJSON
	return u
}

// SetStatus is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetStatus(status string) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.Status)] = status
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) SetUpdatedAt(updatedAt time.Time) PullRequestAnalysisUpdater {
	u.fields[string(PullRequestAnalysisDBSchema.UpdatedAt)] = updatedAt
	return u
}

// StatusEq is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) StatusEq(status string) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("status = ?", status))
}

// StatusIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) StatusIn(status ...string) PullRequestAnalysisQuerySet {
	if len(status) == 0 {
		qs.db.AddError(errors.New("must at least pass one status in StatusIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("status IN (?)", status))
}

// StatusNe is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) StatusNe(status string) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("status != ?", status))
}

// StatusNotIn is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) StatusNotIn(status ...string) PullRequestAnalysisQuerySet {
	if len(status) == 0 {
		qs.db.AddError(errors.New("must at least pass one status in StatusNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("status NOT IN (?)", status))
}

// Update is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u PullRequestAnalysisUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) UpdatedAtEq(updatedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at = ?", updatedAt))
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) UpdatedAtGt(updatedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at > ?", updatedAt))
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) UpdatedAtGte(updatedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at >= ?", updatedAt))
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) UpdatedAtLt(updatedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at < ?", updatedAt))
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) UpdatedAtLte(updatedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at <= ?", updatedAt))
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs PullRequestAnalysisQuerySet) UpdatedAtNe(updatedAt time.Time) PullRequestAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at != ?", updatedAt))
}

// ===== END of query set PullRequestAnalysisQuerySet

// ===== BEGIN of PullRequestAnalysis modifiers

// PullRequestAnalysisDBSchemaField describes database schema field. It requires for method 'Update'
type PullRequestAnalysisDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f PullRequestAnalysisDBSchemaField) String() string {
	return string(f)
}

// PullRequestAnalysisDBSchema stores db field names of PullRequestAnalysis
var PullRequestAnalysisDBSchema = struct {
	ID                      PullRequestAnalysisDBSchemaField
	CreatedAt               PullRequestAnalysisDBSchemaField
	UpdatedAt               PullRequestAnalysisDBSchemaField
	DeletedAt               PullRequestAnalysisDBSchemaField
	GithubRepo              PullRequestAnalysisDBSchemaField
	GithubRepoID            PullRequestAnalysisDBSchemaField
	GithubPullRequestNumber PullRequestAnalysisDBSchemaField
	GithubDeliveryGUID      PullRequestAnalysisDBSchemaField
	CommitSHA               PullRequestAnalysisDBSchemaField
	Status                  PullRequestAnalysisDBSchemaField
	ReportedIssuesCount     PullRequestAnalysisDBSchemaField
	ResultJSON              PullRequestAnalysisDBSchemaField
}{

	ID:                      PullRequestAnalysisDBSchemaField("id"),
	CreatedAt:               PullRequestAnalysisDBSchemaField("created_at"),
	UpdatedAt:               PullRequestAnalysisDBSchemaField("updated_at"),
	DeletedAt:               PullRequestAnalysisDBSchemaField("deleted_at"),
	GithubRepo:              PullRequestAnalysisDBSchemaField("github_repo"),
	GithubRepoID:            PullRequestAnalysisDBSchemaField("github_repo_id"),
	GithubPullRequestNumber: PullRequestAnalysisDBSchemaField("github_pull_request_number"),
	GithubDeliveryGUID:      PullRequestAnalysisDBSchemaField("github_delivery_guid"),
	CommitSHA:               PullRequestAnalysisDBSchemaField("commit_sha"),
	Status:                  PullRequestAnalysisDBSchemaField("status"),
	ReportedIssuesCount:     PullRequestAnalysisDBSchemaField("reported_issues_count"),
	ResultJSON:              PullRequestAnalysisDBSchemaField("result_json"),
}

// Update updates PullRequestAnalysis fields by primary key
// nolint: dupl
func (o *PullRequestAnalysis) Update(db *gorm.DB, fields ...PullRequestAnalysisDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":                         o.ID,
		"created_at":                 o.CreatedAt,
		"updated_at":                 o.UpdatedAt,
		"deleted_at":                 o.DeletedAt,
		"github_repo":                o.GithubRepo,
		"github_repo_id":             o.GithubRepoID,
		"github_pull_request_number": o.GithubPullRequestNumber,
		"github_delivery_guid":       o.GithubDeliveryGUID,
		"commit_sha":                 o.CommitSHA,
		"status":                     o.Status,
		"reported_issues_count":      o.ReportedIssuesCount,
		"result_json":                o.ResultJSON,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update PullRequestAnalysis %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// PullRequestAnalysisUpdater is an PullRequestAnalysis updates manager
type PullRequestAnalysisUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewPullRequestAnalysisUpdater creates new PullRequestAnalysis updater
// nolint: dupl
func NewPullRequestAnalysisUpdater(db *gorm.DB) PullRequestAnalysisUpdater {
	return PullRequestAnalysisUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&PullRequestAnalysis{}),
	}
}

// ===== END of PullRequestAnalysis modifiers

// ===== END of all query sets
