// Code generated by go-queryset. DO NOT EDIT.
package models

import (
	"errors"
	"fmt"
	"time"

	"github.com/jinzhu/gorm"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set GithubAnalysisQuerySet

// GithubAnalysisQuerySet is an queryset type for GithubAnalysis
type GithubAnalysisQuerySet struct {
	db *gorm.DB
}

// NewGithubAnalysisQuerySet constructs new GithubAnalysisQuerySet
func NewGithubAnalysisQuerySet(db *gorm.DB) GithubAnalysisQuerySet {
	return GithubAnalysisQuerySet{
		db: db.Model(&GithubAnalysis{}),
	}
}

func (qs GithubAnalysisQuerySet) w(db *gorm.DB) GithubAnalysisQuerySet {
	return NewGithubAnalysisQuerySet(db)
}

// All is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) All(ret *[]GithubAnalysis) error {
	return qs.db.Find(ret).Error
}

// CommitSHAEq is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) CommitSHAEq(commitSHA string) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("commit_sha = ?", commitSHA))
}

// CommitSHAIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) CommitSHAIn(commitSHA ...string) GithubAnalysisQuerySet {
	if len(commitSHA) == 0 {
		qs.db.AddError(errors.New("must at least pass one commitSHA in CommitSHAIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("commit_sha IN (?)", commitSHA))
}

// CommitSHANe is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) CommitSHANe(commitSHA string) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("commit_sha != ?", commitSHA))
}

// CommitSHANotIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) CommitSHANotIn(commitSHA ...string) GithubAnalysisQuerySet {
	if len(commitSHA) == 0 {
		qs.db.AddError(errors.New("must at least pass one commitSHA in CommitSHANotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("commit_sha NOT IN (?)", commitSHA))
}

// Count is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// Create is an autogenerated method
// nolint: dupl
func (o *GithubAnalysis) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) CreatedAtEq(createdAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at = ?", createdAt))
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) CreatedAtGt(createdAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at > ?", createdAt))
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) CreatedAtGte(createdAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at >= ?", createdAt))
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) CreatedAtLt(createdAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at < ?", createdAt))
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) CreatedAtLte(createdAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at <= ?", createdAt))
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) CreatedAtNe(createdAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("created_at != ?", createdAt))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) Delete() error {
	return qs.db.Delete(GithubAnalysis{}).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *GithubAnalysis) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// DeletedAtEq is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) DeletedAtEq(deletedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at = ?", deletedAt))
}

// DeletedAtGt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) DeletedAtGt(deletedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at > ?", deletedAt))
}

// DeletedAtGte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) DeletedAtGte(deletedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at >= ?", deletedAt))
}

// DeletedAtIsNotNull is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) DeletedAtIsNotNull() GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NOT NULL"))
}

// DeletedAtIsNull is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) DeletedAtIsNull() GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NULL"))
}

// DeletedAtLt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) DeletedAtLt(deletedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at < ?", deletedAt))
}

// DeletedAtLte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) DeletedAtLte(deletedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at <= ?", deletedAt))
}

// DeletedAtNe is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) DeletedAtNe(deletedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("deleted_at != ?", deletedAt))
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GetUpdater() GithubAnalysisUpdater {
	return NewGithubAnalysisUpdater(qs.db)
}

// GithubDeliveryGUIDEq is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubDeliveryGUIDEq(githubDeliveryGUID string) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_delivery_guid = ?", githubDeliveryGUID))
}

// GithubDeliveryGUIDIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubDeliveryGUIDIn(githubDeliveryGUID ...string) GithubAnalysisQuerySet {
	if len(githubDeliveryGUID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubDeliveryGUID in GithubDeliveryGUIDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_delivery_guid IN (?)", githubDeliveryGUID))
}

// GithubDeliveryGUIDNe is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubDeliveryGUIDNe(githubDeliveryGUID string) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_delivery_guid != ?", githubDeliveryGUID))
}

// GithubDeliveryGUIDNotIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubDeliveryGUIDNotIn(githubDeliveryGUID ...string) GithubAnalysisQuerySet {
	if len(githubDeliveryGUID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubDeliveryGUID in GithubDeliveryGUIDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_delivery_guid NOT IN (?)", githubDeliveryGUID))
}

// GithubPullRequestNumberEq is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubPullRequestNumberEq(githubPullRequestNumber int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number = ?", githubPullRequestNumber))
}

// GithubPullRequestNumberGt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubPullRequestNumberGt(githubPullRequestNumber int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number > ?", githubPullRequestNumber))
}

// GithubPullRequestNumberGte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubPullRequestNumberGte(githubPullRequestNumber int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number >= ?", githubPullRequestNumber))
}

// GithubPullRequestNumberIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubPullRequestNumberIn(githubPullRequestNumber ...int) GithubAnalysisQuerySet {
	if len(githubPullRequestNumber) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubPullRequestNumber in GithubPullRequestNumberIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_pull_request_number IN (?)", githubPullRequestNumber))
}

// GithubPullRequestNumberLt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubPullRequestNumberLt(githubPullRequestNumber int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number < ?", githubPullRequestNumber))
}

// GithubPullRequestNumberLte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubPullRequestNumberLte(githubPullRequestNumber int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number <= ?", githubPullRequestNumber))
}

// GithubPullRequestNumberNe is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubPullRequestNumberNe(githubPullRequestNumber int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_pull_request_number != ?", githubPullRequestNumber))
}

// GithubPullRequestNumberNotIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubPullRequestNumberNotIn(githubPullRequestNumber ...int) GithubAnalysisQuerySet {
	if len(githubPullRequestNumber) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubPullRequestNumber in GithubPullRequestNumberNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_pull_request_number NOT IN (?)", githubPullRequestNumber))
}

// GithubRepoIDEq is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubRepoIDEq(githubRepoID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id = ?", githubRepoID))
}

// GithubRepoIDGt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubRepoIDGt(githubRepoID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id > ?", githubRepoID))
}

// GithubRepoIDGte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubRepoIDGte(githubRepoID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id >= ?", githubRepoID))
}

// GithubRepoIDIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubRepoIDIn(githubRepoID ...uint) GithubAnalysisQuerySet {
	if len(githubRepoID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubRepoID in GithubRepoIDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_repo_id IN (?)", githubRepoID))
}

// GithubRepoIDLt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubRepoIDLt(githubRepoID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id < ?", githubRepoID))
}

// GithubRepoIDLte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubRepoIDLte(githubRepoID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id <= ?", githubRepoID))
}

// GithubRepoIDNe is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubRepoIDNe(githubRepoID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("github_repo_id != ?", githubRepoID))
}

// GithubRepoIDNotIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) GithubRepoIDNotIn(githubRepoID ...uint) GithubAnalysisQuerySet {
	if len(githubRepoID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubRepoID in GithubRepoIDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_repo_id NOT IN (?)", githubRepoID))
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) IDEq(ID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("id = ?", ID))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) IDGt(ID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("id > ?", ID))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) IDGte(ID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("id >= ?", ID))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) IDIn(ID ...uint) GithubAnalysisQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id IN (?)", ID))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) IDLt(ID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("id < ?", ID))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) IDLte(ID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("id <= ?", ID))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) IDNe(ID uint) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("id != ?", ID))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) IDNotIn(ID ...uint) GithubAnalysisQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id NOT IN (?)", ID))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) Limit(limit int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) Offset(offset int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs GithubAnalysisQuerySet) One(ret *GithubAnalysis) error {
	return qs.db.First(ret).Error
}

// OrderAscByCreatedAt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderAscByCreatedAt() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("created_at ASC"))
}

// OrderAscByDeletedAt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderAscByDeletedAt() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("deleted_at ASC"))
}

// OrderAscByGithubPullRequestNumber is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderAscByGithubPullRequestNumber() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("github_pull_request_number ASC"))
}

// OrderAscByGithubRepoID is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderAscByGithubRepoID() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("github_repo_id ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderAscByID() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByReportedIssuesCount is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderAscByReportedIssuesCount() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("reported_issues_count ASC"))
}

// OrderAscByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderAscByUpdatedAt() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("updated_at ASC"))
}

// OrderDescByCreatedAt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderDescByCreatedAt() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("created_at DESC"))
}

// OrderDescByDeletedAt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderDescByDeletedAt() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("deleted_at DESC"))
}

// OrderDescByGithubPullRequestNumber is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderDescByGithubPullRequestNumber() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("github_pull_request_number DESC"))
}

// OrderDescByGithubRepoID is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderDescByGithubRepoID() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("github_repo_id DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderDescByID() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByReportedIssuesCount is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderDescByReportedIssuesCount() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("reported_issues_count DESC"))
}

// OrderDescByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) OrderDescByUpdatedAt() GithubAnalysisQuerySet {
	return qs.w(qs.db.Order("updated_at DESC"))
}

// PreloadGithubRepo is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) PreloadGithubRepo() GithubAnalysisQuerySet {
	return qs.w(qs.db.Preload("GithubRepo"))
}

// ReportedIssuesCountEq is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ReportedIssuesCountEq(reportedIssuesCount int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count = ?", reportedIssuesCount))
}

// ReportedIssuesCountGt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ReportedIssuesCountGt(reportedIssuesCount int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count > ?", reportedIssuesCount))
}

// ReportedIssuesCountGte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ReportedIssuesCountGte(reportedIssuesCount int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count >= ?", reportedIssuesCount))
}

// ReportedIssuesCountIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ReportedIssuesCountIn(reportedIssuesCount ...int) GithubAnalysisQuerySet {
	if len(reportedIssuesCount) == 0 {
		qs.db.AddError(errors.New("must at least pass one reportedIssuesCount in ReportedIssuesCountIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("reported_issues_count IN (?)", reportedIssuesCount))
}

// ReportedIssuesCountLt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ReportedIssuesCountLt(reportedIssuesCount int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count < ?", reportedIssuesCount))
}

// ReportedIssuesCountLte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ReportedIssuesCountLte(reportedIssuesCount int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count <= ?", reportedIssuesCount))
}

// ReportedIssuesCountNe is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ReportedIssuesCountNe(reportedIssuesCount int) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("reported_issues_count != ?", reportedIssuesCount))
}

// ReportedIssuesCountNotIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ReportedIssuesCountNotIn(reportedIssuesCount ...int) GithubAnalysisQuerySet {
	if len(reportedIssuesCount) == 0 {
		qs.db.AddError(errors.New("must at least pass one reportedIssuesCount in ReportedIssuesCountNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("reported_issues_count NOT IN (?)", reportedIssuesCount))
}

// ResultJSONEq is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ResultJSONEq(resultJSON []byte) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("result_json = ?", resultJSON))
}

// ResultJSONIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ResultJSONIn(resultJSON ...[]byte) GithubAnalysisQuerySet {
	if len(resultJSON) == 0 {
		qs.db.AddError(errors.New("must at least pass one resultJSON in ResultJSONIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("result_json IN (?)", resultJSON))
}

// ResultJSONNe is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ResultJSONNe(resultJSON []byte) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("result_json != ?", resultJSON))
}

// ResultJSONNotIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) ResultJSONNotIn(resultJSON ...[]byte) GithubAnalysisQuerySet {
	if len(resultJSON) == 0 {
		qs.db.AddError(errors.New("must at least pass one resultJSON in ResultJSONNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("result_json NOT IN (?)", resultJSON))
}

// SetCommitSHA is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetCommitSHA(commitSHA string) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.CommitSHA)] = commitSHA
	return u
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetCreatedAt(createdAt time.Time) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.CreatedAt)] = createdAt
	return u
}

// SetDeletedAt is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetDeletedAt(deletedAt *time.Time) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.DeletedAt)] = deletedAt
	return u
}

// SetGithubDeliveryGUID is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetGithubDeliveryGUID(githubDeliveryGUID string) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.GithubDeliveryGUID)] = githubDeliveryGUID
	return u
}

// SetGithubPullRequestNumber is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetGithubPullRequestNumber(githubPullRequestNumber int) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.GithubPullRequestNumber)] = githubPullRequestNumber
	return u
}

// SetGithubRepo is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetGithubRepo(githubRepo GithubRepo) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.GithubRepo)] = githubRepo
	return u
}

// SetGithubRepoID is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetGithubRepoID(githubRepoID uint) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.GithubRepoID)] = githubRepoID
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetID(ID uint) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.ID)] = ID
	return u
}

// SetReportedIssuesCount is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetReportedIssuesCount(reportedIssuesCount int) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.ReportedIssuesCount)] = reportedIssuesCount
	return u
}

// SetResultJSON is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetResultJSON(resultJSON []byte) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.ResultJSON)] = resultJSON
	return u
}

// SetStatus is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetStatus(status string) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.Status)] = status
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) SetUpdatedAt(updatedAt time.Time) GithubAnalysisUpdater {
	u.fields[string(GithubAnalysisDBSchema.UpdatedAt)] = updatedAt
	return u
}

// StatusEq is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) StatusEq(status string) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("status = ?", status))
}

// StatusIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) StatusIn(status ...string) GithubAnalysisQuerySet {
	if len(status) == 0 {
		qs.db.AddError(errors.New("must at least pass one status in StatusIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("status IN (?)", status))
}

// StatusNe is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) StatusNe(status string) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("status != ?", status))
}

// StatusNotIn is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) StatusNotIn(status ...string) GithubAnalysisQuerySet {
	if len(status) == 0 {
		qs.db.AddError(errors.New("must at least pass one status in StatusNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("status NOT IN (?)", status))
}

// Update is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u GithubAnalysisUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) UpdatedAtEq(updatedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at = ?", updatedAt))
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) UpdatedAtGt(updatedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at > ?", updatedAt))
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) UpdatedAtGte(updatedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at >= ?", updatedAt))
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) UpdatedAtLt(updatedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at < ?", updatedAt))
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) UpdatedAtLte(updatedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at <= ?", updatedAt))
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs GithubAnalysisQuerySet) UpdatedAtNe(updatedAt time.Time) GithubAnalysisQuerySet {
	return qs.w(qs.db.Where("updated_at != ?", updatedAt))
}

// ===== END of query set GithubAnalysisQuerySet

// ===== BEGIN of GithubAnalysis modifiers

// GithubAnalysisDBSchemaField describes database schema field. It requires for method 'Update'
type GithubAnalysisDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f GithubAnalysisDBSchemaField) String() string {
	return string(f)
}

// GithubAnalysisDBSchema stores db field names of GithubAnalysis
var GithubAnalysisDBSchema = struct {
	ID                      GithubAnalysisDBSchemaField
	CreatedAt               GithubAnalysisDBSchemaField
	UpdatedAt               GithubAnalysisDBSchemaField
	DeletedAt               GithubAnalysisDBSchemaField
	GithubRepo              GithubAnalysisDBSchemaField
	GithubRepoID            GithubAnalysisDBSchemaField
	GithubPullRequestNumber GithubAnalysisDBSchemaField
	GithubDeliveryGUID      GithubAnalysisDBSchemaField
	CommitSHA               GithubAnalysisDBSchemaField
	Status                  GithubAnalysisDBSchemaField
	ReportedIssuesCount     GithubAnalysisDBSchemaField
	ResultJSON              GithubAnalysisDBSchemaField
}{

	ID:                      GithubAnalysisDBSchemaField("id"),
	CreatedAt:               GithubAnalysisDBSchemaField("created_at"),
	UpdatedAt:               GithubAnalysisDBSchemaField("updated_at"),
	DeletedAt:               GithubAnalysisDBSchemaField("deleted_at"),
	GithubRepo:              GithubAnalysisDBSchemaField("github_repo"),
	GithubRepoID:            GithubAnalysisDBSchemaField("github_repo_id"),
	GithubPullRequestNumber: GithubAnalysisDBSchemaField("github_pull_request_number"),
	GithubDeliveryGUID:      GithubAnalysisDBSchemaField("github_delivery_guid"),
	CommitSHA:               GithubAnalysisDBSchemaField("commit_sha"),
	Status:                  GithubAnalysisDBSchemaField("status"),
	ReportedIssuesCount:     GithubAnalysisDBSchemaField("reported_issues_count"),
	ResultJSON:              GithubAnalysisDBSchemaField("result_json"),
}

// Update updates GithubAnalysis fields by primary key
// nolint: dupl
func (o *GithubAnalysis) Update(db *gorm.DB, fields ...GithubAnalysisDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":                         o.ID,
		"created_at":                 o.CreatedAt,
		"updated_at":                 o.UpdatedAt,
		"deleted_at":                 o.DeletedAt,
		"github_repo":                o.GithubRepo,
		"github_repo_id":             o.GithubRepoID,
		"github_pull_request_number": o.GithubPullRequestNumber,
		"github_delivery_guid":       o.GithubDeliveryGUID,
		"commit_sha":                 o.CommitSHA,
		"status":                     o.Status,
		"reported_issues_count":      o.ReportedIssuesCount,
		"result_json":                o.ResultJSON,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update GithubAnalysis %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// GithubAnalysisUpdater is an GithubAnalysis updates manager
type GithubAnalysisUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewGithubAnalysisUpdater creates new GithubAnalysis updater
// nolint: dupl
func NewGithubAnalysisUpdater(db *gorm.DB) GithubAnalysisUpdater {
	return GithubAnalysisUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&GithubAnalysis{}),
	}
}

// ===== END of GithubAnalysis modifiers

// ===== END of all query sets
