// Code generated by go-queryset. DO NOT EDIT.
package models

import (
	"errors"
	"fmt"
	"time"

	"github.com/jinzhu/gorm"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set GithubRepoQuerySet

// GithubRepoQuerySet is an queryset type for GithubRepo
type GithubRepoQuerySet struct {
	db *gorm.DB
}

// NewGithubRepoQuerySet constructs new GithubRepoQuerySet
func NewGithubRepoQuerySet(db *gorm.DB) GithubRepoQuerySet {
	return GithubRepoQuerySet{
		db: db.Model(&GithubRepo{}),
	}
}

func (qs GithubRepoQuerySet) w(db *gorm.DB) GithubRepoQuerySet {
	return NewGithubRepoQuerySet(db)
}

// All is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) All(ret *[]GithubRepo) error {
	return qs.db.Find(ret).Error
}

// Count is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// Create is an autogenerated method
// nolint: dupl
func (o *GithubRepo) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) CreatedAtEq(createdAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("created_at = ?", createdAt))
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) CreatedAtGt(createdAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("created_at > ?", createdAt))
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) CreatedAtGte(createdAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("created_at >= ?", createdAt))
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) CreatedAtLt(createdAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("created_at < ?", createdAt))
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) CreatedAtLte(createdAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("created_at <= ?", createdAt))
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) CreatedAtNe(createdAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("created_at != ?", createdAt))
}

// Delete is an autogenerated method
// nolint: dupl
func (o *GithubRepo) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) Delete() error {
	return qs.db.Delete(GithubRepo{}).Error
}

// DeletedAtEq is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DeletedAtEq(deletedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("deleted_at = ?", deletedAt))
}

// DeletedAtGt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DeletedAtGt(deletedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("deleted_at > ?", deletedAt))
}

// DeletedAtGte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DeletedAtGte(deletedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("deleted_at >= ?", deletedAt))
}

// DeletedAtIsNotNull is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DeletedAtIsNotNull() GithubRepoQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NOT NULL"))
}

// DeletedAtIsNull is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DeletedAtIsNull() GithubRepoQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NULL"))
}

// DeletedAtLt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DeletedAtLt(deletedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("deleted_at < ?", deletedAt))
}

// DeletedAtLte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DeletedAtLte(deletedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("deleted_at <= ?", deletedAt))
}

// DeletedAtNe is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DeletedAtNe(deletedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("deleted_at != ?", deletedAt))
}

// DisplayNameEq is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DisplayNameEq(displayName string) GithubRepoQuerySet {
	return qs.w(qs.db.Where("display_name = ?", displayName))
}

// DisplayNameIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DisplayNameIn(displayName ...string) GithubRepoQuerySet {
	if len(displayName) == 0 {
		qs.db.AddError(errors.New("must at least pass one displayName in DisplayNameIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("display_name IN (?)", displayName))
}

// DisplayNameNe is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DisplayNameNe(displayName string) GithubRepoQuerySet {
	return qs.w(qs.db.Where("display_name != ?", displayName))
}

// DisplayNameNotIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) DisplayNameNotIn(displayName ...string) GithubRepoQuerySet {
	if len(displayName) == 0 {
		qs.db.AddError(errors.New("must at least pass one displayName in DisplayNameNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("display_name NOT IN (?)", displayName))
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GetUpdater() GithubRepoUpdater {
	return NewGithubRepoUpdater(qs.db)
}

// GithubHookIDEq is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubHookIDEq(githubHookID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_hook_id = ?", githubHookID))
}

// GithubHookIDGt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubHookIDGt(githubHookID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_hook_id > ?", githubHookID))
}

// GithubHookIDGte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubHookIDGte(githubHookID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_hook_id >= ?", githubHookID))
}

// GithubHookIDIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubHookIDIn(githubHookID ...int) GithubRepoQuerySet {
	if len(githubHookID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubHookID in GithubHookIDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_hook_id IN (?)", githubHookID))
}

// GithubHookIDLt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubHookIDLt(githubHookID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_hook_id < ?", githubHookID))
}

// GithubHookIDLte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubHookIDLte(githubHookID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_hook_id <= ?", githubHookID))
}

// GithubHookIDNe is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubHookIDNe(githubHookID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_hook_id != ?", githubHookID))
}

// GithubHookIDNotIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubHookIDNotIn(githubHookID ...int) GithubRepoQuerySet {
	if len(githubHookID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubHookID in GithubHookIDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_hook_id NOT IN (?)", githubHookID))
}

// GithubIDEq is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubIDEq(githubID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_id = ?", githubID))
}

// GithubIDGt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubIDGt(githubID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_id > ?", githubID))
}

// GithubIDGte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubIDGte(githubID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_id >= ?", githubID))
}

// GithubIDIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubIDIn(githubID ...int) GithubRepoQuerySet {
	if len(githubID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubID in GithubIDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_id IN (?)", githubID))
}

// GithubIDLt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubIDLt(githubID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_id < ?", githubID))
}

// GithubIDLte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubIDLte(githubID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_id <= ?", githubID))
}

// GithubIDNe is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubIDNe(githubID int) GithubRepoQuerySet {
	return qs.w(qs.db.Where("github_id != ?", githubID))
}

// GithubIDNotIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) GithubIDNotIn(githubID ...int) GithubRepoQuerySet {
	if len(githubID) == 0 {
		qs.db.AddError(errors.New("must at least pass one githubID in GithubIDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("github_id NOT IN (?)", githubID))
}

// HookIDEq is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) HookIDEq(hookID string) GithubRepoQuerySet {
	return qs.w(qs.db.Where("hook_id = ?", hookID))
}

// HookIDIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) HookIDIn(hookID ...string) GithubRepoQuerySet {
	if len(hookID) == 0 {
		qs.db.AddError(errors.New("must at least pass one hookID in HookIDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("hook_id IN (?)", hookID))
}

// HookIDNe is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) HookIDNe(hookID string) GithubRepoQuerySet {
	return qs.w(qs.db.Where("hook_id != ?", hookID))
}

// HookIDNotIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) HookIDNotIn(hookID ...string) GithubRepoQuerySet {
	if len(hookID) == 0 {
		qs.db.AddError(errors.New("must at least pass one hookID in HookIDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("hook_id NOT IN (?)", hookID))
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) IDEq(ID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("id = ?", ID))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) IDGt(ID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("id > ?", ID))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) IDGte(ID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("id >= ?", ID))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) IDIn(ID ...uint) GithubRepoQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id IN (?)", ID))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) IDLt(ID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("id < ?", ID))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) IDLte(ID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("id <= ?", ID))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) IDNe(ID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("id != ?", ID))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) IDNotIn(ID ...uint) GithubRepoQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id NOT IN (?)", ID))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) Limit(limit int) GithubRepoQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// NameEq is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) NameEq(name string) GithubRepoQuerySet {
	return qs.w(qs.db.Where("name = ?", name))
}

// NameIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) NameIn(name ...string) GithubRepoQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in NameIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("name IN (?)", name))
}

// NameNe is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) NameNe(name string) GithubRepoQuerySet {
	return qs.w(qs.db.Where("name != ?", name))
}

// NameNotIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) NameNotIn(name ...string) GithubRepoQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in NameNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("name NOT IN (?)", name))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) Offset(offset int) GithubRepoQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs GithubRepoQuerySet) One(ret *GithubRepo) error {
	return qs.db.First(ret).Error
}

// OrderAscByCreatedAt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderAscByCreatedAt() GithubRepoQuerySet {
	return qs.w(qs.db.Order("created_at ASC"))
}

// OrderAscByDeletedAt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderAscByDeletedAt() GithubRepoQuerySet {
	return qs.w(qs.db.Order("deleted_at ASC"))
}

// OrderAscByGithubHookID is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderAscByGithubHookID() GithubRepoQuerySet {
	return qs.w(qs.db.Order("github_hook_id ASC"))
}

// OrderAscByGithubID is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderAscByGithubID() GithubRepoQuerySet {
	return qs.w(qs.db.Order("github_id ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderAscByID() GithubRepoQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderAscByUpdatedAt() GithubRepoQuerySet {
	return qs.w(qs.db.Order("updated_at ASC"))
}

// OrderAscByUserID is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderAscByUserID() GithubRepoQuerySet {
	return qs.w(qs.db.Order("user_id ASC"))
}

// OrderDescByCreatedAt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderDescByCreatedAt() GithubRepoQuerySet {
	return qs.w(qs.db.Order("created_at DESC"))
}

// OrderDescByDeletedAt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderDescByDeletedAt() GithubRepoQuerySet {
	return qs.w(qs.db.Order("deleted_at DESC"))
}

// OrderDescByGithubHookID is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderDescByGithubHookID() GithubRepoQuerySet {
	return qs.w(qs.db.Order("github_hook_id DESC"))
}

// OrderDescByGithubID is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderDescByGithubID() GithubRepoQuerySet {
	return qs.w(qs.db.Order("github_id DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderDescByID() GithubRepoQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderDescByUpdatedAt() GithubRepoQuerySet {
	return qs.w(qs.db.Order("updated_at DESC"))
}

// OrderDescByUserID is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) OrderDescByUserID() GithubRepoQuerySet {
	return qs.w(qs.db.Order("user_id DESC"))
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) SetCreatedAt(createdAt time.Time) GithubRepoUpdater {
	u.fields[string(GithubRepoDBSchema.CreatedAt)] = createdAt
	return u
}

// SetDeletedAt is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) SetDeletedAt(deletedAt *time.Time) GithubRepoUpdater {
	u.fields[string(GithubRepoDBSchema.DeletedAt)] = deletedAt
	return u
}

// SetDisplayName is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) SetDisplayName(displayName string) GithubRepoUpdater {
	u.fields[string(GithubRepoDBSchema.DisplayName)] = displayName
	return u
}

// SetGithubHookID is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) SetGithubHookID(githubHookID int) GithubRepoUpdater {
	u.fields[string(GithubRepoDBSchema.GithubHookID)] = githubHookID
	return u
}

// SetGithubID is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) SetGithubID(githubID int) GithubRepoUpdater {
	u.fields[string(GithubRepoDBSchema.GithubID)] = githubID
	return u
}

// SetHookID is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) SetHookID(hookID string) GithubRepoUpdater {
	u.fields[string(GithubRepoDBSchema.HookID)] = hookID
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) SetID(ID uint) GithubRepoUpdater {
	u.fields[string(GithubRepoDBSchema.ID)] = ID
	return u
}

// SetName is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) SetName(name string) GithubRepoUpdater {
	u.fields[string(GithubRepoDBSchema.Name)] = name
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) SetUpdatedAt(updatedAt time.Time) GithubRepoUpdater {
	u.fields[string(GithubRepoDBSchema.UpdatedAt)] = updatedAt
	return u
}

// SetUserID is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) SetUserID(userID uint) GithubRepoUpdater {
	u.fields[string(GithubRepoDBSchema.UserID)] = userID
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u GithubRepoUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UpdatedAtEq(updatedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("updated_at = ?", updatedAt))
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UpdatedAtGt(updatedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("updated_at > ?", updatedAt))
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UpdatedAtGte(updatedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("updated_at >= ?", updatedAt))
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UpdatedAtLt(updatedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("updated_at < ?", updatedAt))
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UpdatedAtLte(updatedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("updated_at <= ?", updatedAt))
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UpdatedAtNe(updatedAt time.Time) GithubRepoQuerySet {
	return qs.w(qs.db.Where("updated_at != ?", updatedAt))
}

// UserIDEq is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UserIDEq(userID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("user_id = ?", userID))
}

// UserIDGt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UserIDGt(userID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("user_id > ?", userID))
}

// UserIDGte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UserIDGte(userID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("user_id >= ?", userID))
}

// UserIDIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UserIDIn(userID ...uint) GithubRepoQuerySet {
	if len(userID) == 0 {
		qs.db.AddError(errors.New("must at least pass one userID in UserIDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("user_id IN (?)", userID))
}

// UserIDLt is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UserIDLt(userID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("user_id < ?", userID))
}

// UserIDLte is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UserIDLte(userID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("user_id <= ?", userID))
}

// UserIDNe is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UserIDNe(userID uint) GithubRepoQuerySet {
	return qs.w(qs.db.Where("user_id != ?", userID))
}

// UserIDNotIn is an autogenerated method
// nolint: dupl
func (qs GithubRepoQuerySet) UserIDNotIn(userID ...uint) GithubRepoQuerySet {
	if len(userID) == 0 {
		qs.db.AddError(errors.New("must at least pass one userID in UserIDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("user_id NOT IN (?)", userID))
}

// ===== END of query set GithubRepoQuerySet

// ===== BEGIN of GithubRepo modifiers

// GithubRepoDBSchemaField describes database schema field. It requires for method 'Update'
type GithubRepoDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f GithubRepoDBSchemaField) String() string {
	return string(f)
}

// GithubRepoDBSchema stores db field names of GithubRepo
var GithubRepoDBSchema = struct {
	ID           GithubRepoDBSchemaField
	CreatedAt    GithubRepoDBSchemaField
	UpdatedAt    GithubRepoDBSchemaField
	DeletedAt    GithubRepoDBSchemaField
	UserID       GithubRepoDBSchemaField
	Name         GithubRepoDBSchemaField
	DisplayName  GithubRepoDBSchemaField
	HookID       GithubRepoDBSchemaField
	GithubHookID GithubRepoDBSchemaField
	GithubID     GithubRepoDBSchemaField
}{

	ID:           GithubRepoDBSchemaField("id"),
	CreatedAt:    GithubRepoDBSchemaField("created_at"),
	UpdatedAt:    GithubRepoDBSchemaField("updated_at"),
	DeletedAt:    GithubRepoDBSchemaField("deleted_at"),
	UserID:       GithubRepoDBSchemaField("user_id"),
	Name:         GithubRepoDBSchemaField("name"),
	DisplayName:  GithubRepoDBSchemaField("display_name"),
	HookID:       GithubRepoDBSchemaField("hook_id"),
	GithubHookID: GithubRepoDBSchemaField("github_hook_id"),
	GithubID:     GithubRepoDBSchemaField("github_id"),
}

// Update updates GithubRepo fields by primary key
// nolint: dupl
func (o *GithubRepo) Update(db *gorm.DB, fields ...GithubRepoDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":             o.ID,
		"created_at":     o.CreatedAt,
		"updated_at":     o.UpdatedAt,
		"deleted_at":     o.DeletedAt,
		"user_id":        o.UserID,
		"name":           o.Name,
		"display_name":   o.DisplayName,
		"hook_id":        o.HookID,
		"github_hook_id": o.GithubHookID,
		"github_id":      o.GithubID,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update GithubRepo %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// GithubRepoUpdater is an GithubRepo updates manager
type GithubRepoUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewGithubRepoUpdater creates new GithubRepo updater
// nolint: dupl
func NewGithubRepoUpdater(db *gorm.DB) GithubRepoUpdater {
	return GithubRepoUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&GithubRepo{}),
	}
}

// ===== END of GithubRepo modifiers

// ===== END of all query sets
