// Code generated by genservices. DO NOT EDIT.
package subscription

import (
	"context"
	"runtime/debug"

	"github.com/go-kit/kit/endpoint"
	"github.com/golangci/golangci-api/internal/api/apierrors"
	"github.com/golangci/golangci-api/internal/api/endpointutil"
	"github.com/golangci/golangci-api/internal/shared/logutil"
	"github.com/golangci/golangci-api/pkg/api/request"
	"github.com/golangci/golangci-api/pkg/api/returntypes"
	"github.com/pkg/errors"
)

type GetRequest struct {
	ReqOrg *request.Org
}

type GetResponse struct {
	err error
	*returntypes.SubInfo
}

func makeGetEndpoint(svc Service, log logutil.Log) endpoint.Endpoint {
	return func(ctx context.Context, reqObj interface{}) (resp interface{}, err error) {

		req := reqObj.(GetRequest)

		reqLogger := log
		defer func() {
			if rerr := recover(); rerr != nil {
				reqLogger.Errorf("Panic occured")
				reqLogger.Infof("%s", debug.Stack())
				resp = GetResponse{
					err: errors.New("panic occured"),
				}
				err = nil
			}
		}()

		if err := endpointutil.Error(ctx); err != nil {
			log.Warnf("Error occurred during request context creation: %s", err)
			resp = GetResponse{
				err: err,
			}
			return resp, nil
		}

		rc := endpointutil.RequestContext(ctx).(*request.AuthorizedContext)
		reqLogger = rc.Log

		req.ReqOrg.FillLogContext(rc.Lctx)

		v, err := svc.Get(rc, req.ReqOrg)
		if err != nil {
			rc.Log.Errorf("subscription.Service.Get failed: %s", err)
			return GetResponse{err, v}, nil
		}

		return GetResponse{nil, v}, nil

	}
}

type UpdateRequest struct {
	ReqOrg  *request.Org
	Payload *UpdatePayload
}

type UpdateResponse struct {
	err error
}

func makeUpdateEndpoint(svc Service, log logutil.Log) endpoint.Endpoint {
	return func(ctx context.Context, reqObj interface{}) (resp interface{}, err error) {

		req := reqObj.(UpdateRequest)

		reqLogger := log
		defer func() {
			if rerr := recover(); rerr != nil {
				reqLogger.Errorf("Panic occured")
				reqLogger.Infof("%s", debug.Stack())
				resp = UpdateResponse{
					err: errors.New("panic occured"),
				}
				err = nil
			}
		}()

		if err := endpointutil.Error(ctx); err != nil {
			log.Warnf("Error occurred during request context creation: %s", err)
			resp = UpdateResponse{
				err: err,
			}
			return resp, nil
		}

		rc := endpointutil.RequestContext(ctx).(*request.AuthorizedContext)
		reqLogger = rc.Log

		req.ReqOrg.FillLogContext(rc.Lctx)
		req.Payload.FillLogContext(rc.Lctx)

		err = svc.Update(rc, req.ReqOrg, req.Payload)
		if err != nil {
			if !apierrors.IsErrorLikeResult(err) {
				rc.Log.Errorf("subscription.Service.Update failed: %s", err)
			}
			return UpdateResponse{err}, nil
		}

		return UpdateResponse{nil}, nil

	}
}

type EventCreateRequest struct {
	Context *EventRequestContext
	Body    request.Body
}

type EventCreateResponse struct {
	err error
}

func makeEventCreateEndpoint(svc Service, log logutil.Log) endpoint.Endpoint {
	return func(ctx context.Context, reqObj interface{}) (resp interface{}, err error) {

		req := reqObj.(EventCreateRequest)

		reqLogger := log
		defer func() {
			if rerr := recover(); rerr != nil {
				reqLogger.Errorf("Panic occured")
				reqLogger.Infof("%s", debug.Stack())
				resp = EventCreateResponse{
					err: errors.New("panic occured"),
				}
				err = nil
			}
		}()

		if err := endpointutil.Error(ctx); err != nil {
			log.Warnf("Error occurred during request context creation: %s", err)
			resp = EventCreateResponse{
				err: err,
			}
			return resp, nil
		}

		rc := endpointutil.RequestContext(ctx).(*request.AnonymousContext)
		reqLogger = rc.Log

		req.Context.FillLogContext(rc.Lctx)
		req.Body.FillLogContext(rc.Lctx)

		err = svc.EventCreate(rc, req.Context, req.Body)
		if err != nil {
			if !apierrors.IsErrorLikeResult(err) {
				rc.Log.Errorf("subscription.Service.EventCreate failed: %s", err)
			}
			return EventCreateResponse{err}, nil
		}

		return EventCreateResponse{nil}, nil

	}
}
